### PR TITLE
Fix remap list

### LINKED ISSUE #45: RemapImports is missing a translation for various EEI methods

### PR DESCRIPTION
**Pull request by jakelang**
Closes #45

### CODE REVIEW

File: libchisel/src/remapimports.rs [hunk 1]
```diff
@@ -101,6 +137,10 @@ impl Translations {
                         ImportPair::new("env", "ethereum_storageLoad"),
                         ImportPair::new("ethereum", "storageLoad"),
                     ),
+                    (
+                        ImportPair::new("env", "ethereum_log"),
```
Comment (axic) [inline libchisel/src/remapimports.rs]: Why is this inbetween storage?
