### PR TITLE
Fix indexing in VerifyImports

### LINKED ISSUE #47: VerifyImports fails on code that has been transformed by RemapImports
For example:
```wat
(module
  (memory 1)
  (type (;0;) (func (result i64)))
  (import "ethereum" "getGasLeft" (type 0))
  (func $main)
  (export "main" (func $main))
  (export "memory" (memory 0))
)
```

### PR DESCRIPTION
**Pull request by jakelang**
Closes #47.

### CODE REVIEW

File: libchisel/src/verifyimports.rs [hunk 1]
```diff
@@ -169,7 +169,7 @@ impl<'a> ImportCheck for ImportType<'a> {
                                 ImportStatus::Malformed
                             }
                         } else {
-                            ImportStatus::Malformed
+                            panic!(); // This should never happen.
```
Comment (axic) [inline libchisel/src/verifyimports.rs]: Instead of `panic!()` here cannot you just do `let sig = func_sig.unwrap()`?

Comment (axic) [reply libchisel/src/verifyimports.rs]: Or even `.expect`

Comment (jakelang) [reply libchisel/src/verifyimports.rs]: Will do
