### PR TITLE
Grow deployer's memory to size

### LINKED ISSUE #53: Deployer: fix memory size
The deployer has a fixed 1 page memory size (this applies to both the memory and the custom section deployre). Likely it will fail with larger contacts. This needs to be fixed and tested for.

### PR DESCRIPTION
**Pull request by s1na**
Fixes #53

### CODE REVIEW

File: libchisel/src/deployer.rs [hunk 1]
```diff
@@ -38,6 +38,9 @@ impl<'a> Deployer<'a> {
     (local $payload_size i32)
     (set_local $size (call $getCodeSize))
 
+    ;; grow memory to fit code; assumes 1 initial page
+    (call $growToSize (get_local $size))
```
Comment (axic) [inline libchisel/src/deployer.rs]: I think instead of this we may be better off using the module builder and then we can just change `(memory 1)`. What do you think?

File: libchisel/src/deployer.rs [hunk 2]
```diff
@@ -50,17 +53,30 @@ impl<'a> Deployer<'a> {
...
   )
+
+  (func $growToSize (param i32)
+    (local $pages i32)
+    ;; pages = size / 2^16
+    ;; assumes current memory size is 1 page
+    (set_local $pages (i32.shr_u (get_local 0) (i32.const 16)))
+    ;; throw if growing memory failed
+    (if
+      (i32.eq (memory.grow (get_local $pages)) (i32.const -1))
```
Comment (axic) [inline libchisel/src/deployer.rs]: Why not just `i32.const 65536` instead of this pages stuff?

File: libchisel/src/deployer.rs (hunk 1 above)
Comment (s1na) [reply libchisel/src/deployer.rs]: That makes more sense, it'll also have less runtime cost. Will update.

Comment (s1na) [reply libchisel/src/deployer.rs]: Couldn't use builder to modify existing memory. Modified the module in-place.

**Comment by axic** [comment]
Nice! 

Can you also update the memory deployer? You only did the custom section deployer.

**Comment by s1na** [comment]
Sorry, updated. 

I kind of had the wrong impression that wasm engines would extend memory for the data section...

**Comment by axic** [comment]
> I kind of had the wrong impression that wasm engines would extend memory for the data section...

Tbh I'm not sure, need to validate both cases. But having the bigger memory explicitly cannot hurt.
